### PR TITLE
Initial documentation of the problem types.

### PR DESCRIPTION
**Pull request by Sbte**

### CODE REVIEW

**Comment by Sbte** [comment]
Hi Lourens, no need to read the actual documentation, but I'd like your thoughts on if I did anything obviously wrong in the configuration.

**Review by LourensVeen — APPROVED** [review]
Looks good to me! Note that you can [configure RTD to build for PRs](https://docs.readthedocs.io/en/stable/guides/pull-requests.html), allowing you to check that it works and preview the result. I've never used it actually, but I'm going to next time I do something with documentation in one of my repos.

**Comment by Sbte** [comment]
Thanks. I'll try to set up RTD right now.

**Comment by Sbte** [comment]
It's available here now: https://transiflow.readthedocs.io/

I'm about 90% done with the documentation, so I'll keep merging that over the coming week. Then I'll look into the release process. Thanks for the help!

**Pull request merged**
